#!/usr/bin/env bash
LEVEL_NO=27
PASSWORD=3ba3118a22e93127a4ed485be72ef5ea
figlet "level ${LEVEL_NO}"
echo "pass is ${PASSWORD}"
echo -n "${PASSWORD}" | pbcopy

cat << 'HEARDOK'
do this:

cd /tmp/epiccoleman27
git clone ssh://bandit27-git@localhost/home/bandit27-git/repo
cat repo/README

ssh -p 2220 bandit${LEVEL_NO}@bandit.labs.overthewire.org
HEARDOK
